use_frameworks!

target 'HFSuperImages_Example' do
  pod 'HFSuperImages', :path => '../'

  target 'HFSuperImages_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
